#include "pins.h"

static pin_t * all_pins[NUM_PINS];
static pin_group_t * output_pins;

void initPins(void)
{
	// generated by pin-map.py config using pin-map.json

	// axon 1 excit A8
	all_pins[0]->address = initPinAddress(PORT_AXON1_EX, PIN_AXON1_EX);
	all_pins[0]->pin_type = EXCIT;
	all_pins[0]->port_type = AXON;
	all_pins[0]->exti = PIN_AXON1_EX;
	setPinAsOutput(all_pins[0]);
}

static pin_address_t * initPinAddress(uint32_t port, uint32_t pin)
{
    pin_address_t * address = malloc(sizeof(pin_address_t));
    pin_address_t address_init = {port, pin};
    memcpy(address, &address_init, sizeof(pin_address_t));
    return address;
}

pin_group_t * getOutputPins(void)
{
    return output_pins;
}

void selectOutputPins(pin_group_name_t output_group_name)
{
    uint8_t i;

    switch(output_group_name){
        case AXONS:
            ouput_pins->num_pins = NUM_AXONS;
            realloc(output_pins->pins, sizeof(pin_t *) * output_pins->num_pins);
            memcpy(output_pins->pins, axon_output_pins);
            break;
        default:
            break;
    }
}